# ====== 0.1B ======
# DECO (BlockFFN-v2)
export EXP_NAME=blockffn_01b_mul1002_withmean_d64_s128_lr1175e3_b64; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_blockffn_nomup/blockffn_01b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 42 --moe-ffn-hidden-size 64 --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.002 --expert-act-func norm_silu --expert-not-gated --lr 1.1175e-3 --global-batch-size 64 --micro-batch-size 8 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# Dense
export EXP_NAME=dense_01b_lr1175e3_b64; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_dense_nomup/dense_01b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --lr 1.1175e-3 --global-batch-size 64 --micro-batch-size 8 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# ReMoE
export EXP_NAME=remoe_01b_mul105_d64_s128_nongated_lr1175e3_b64; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_remoe_nomup/remoe_01b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 44 --moe-ffn-hidden-size 61 --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.05 --expert-not-gated --lr 1.1175e-3 --global-batch-size 64 --micro-batch-size 8 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# BlockFFN (v1)
export EXP_NAME=blockv1_01b_mul1002_d64_s128_lr1175e3_b64; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_blockffn_v1_nomup/blockv1_01b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 42 --moe-ffn-hidden-size 64 --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.002 --expert-not-gated --lr 1.1175e-3 --global-batch-size 64 --micro-batch-size 8 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# DeepSeek
export EXP_NAME=deepseek_01b_d64_s128_gated_lr1175e3_b64; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_deepseek_nomup/deepseek_01b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --num-experts 44 --moe-router-topk 9 --moe-ffn-hidden-size 41 --moe-shared-expert-intermediate-size 128 --lr 1.1175e-3 --global-batch-size 64 --micro-batch-size 8 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# TopP
export EXP_NAME=topp_01b_d64_s128_nongated_p06_lr1175e3_b64; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_topp_nomup/topp_01b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --num-experts 44 --moe-router-topp 0.6 --moe-ffn-hidden-size 61 --moe-shared-expert-intermediate-size 128 --expert-not-gated --lr 1.1175e-3 --global-batch-size 64 --micro-batch-size 8 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# ====== 0.2B ======
# DECO (BlockFFN-v2)
export EXP_NAME=blockffn_02b_mul1002_withmean_d64_s128_lr93e4_b128; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_blockffn_nomup/blockffn_02b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 57 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.002 --expert-act-func norm_silu --lr 9.3e-4 --global-batch-size 128 --micro-batch-size 16 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# Dense
export EXP_NAME=dense_02b_lr93e4_b128; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_dense_nomup/dense_02b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --lr 9.3e-4 --global-batch-size 128 --micro-batch-size 16 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# DeepSeek
export EXP_NAME=deepseek_02b_d64_s128_gated_lr93e4_b128; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_deepseek_nomup/deepseek_02b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 59 --moe-ffn-hidden-size 41 --moe-router-topk 12 --lr 9.3e-4 --global-batch-size 128 --micro-batch-size 16 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# ReMoE
export EXP_NAME=remoe_02b_mul105_d64_s128_nongated_lr93e4_b128; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_remoe_nomup/remoe_02b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 59 --moe-ffn-hidden-size 62 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.05 --lr 9.3e-4 --global-batch-size 128 --micro-batch-size 8 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# BlockFFN (v1)
export EXP_NAME=blockv1_02b_mul1002_d64_s128_lr93e4_b128; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_blockffn_v1_nomup/blockv1_02b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 57 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.002 --lr 9.3e-4 --global-batch-size 128 --micro-batch-size 16 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# TopP
export EXP_NAME=topp_02b_d64_s128_nongated_p06_lr93e4_b128; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=1 RANK=0 bash examples/blockffn/scaling_topp_nomup/topp_02b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 59 --moe-ffn-hidden-size 62 --moe-router-topp 0.6 --expert-not-gated --lr 9.3e-4 --global-batch-size 128 --micro-batch-size 16 --train-iters 15000 --lr-decay-iters 15000 --lr-wsd-decay-iters 1000

# ====== 0.5B ======
# DECO (BlockFFN-v2)
export EXP_NAME=blockffn_05b_mul1001_withmean_d64_s128_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_blockffn_nomup/blockffn_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 77 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.001 --expert-act-func norm_silu --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 16
export EXP_NAME=blockffn_05b_mul1001_withmean_d64_s128_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_blockffn_nomup/blockffn_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 77 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.001 --expert-act-func norm_silu --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 16

# Dense
export EXP_NAME=dense_05b_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_dense_nomup/dense_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 16 --seed 1
export EXP_NAME=dense_05b_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_dense_nomup/dense_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 16 --seed 1

# ReMoE
export EXP_NAME=remoe_05b_mul105_d64_s128_nongated_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_remoe_nomup/remoe_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 79 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.05 --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 4
export EXP_NAME=remoe_05b_mul105_d64_s128_nongated_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_remoe_nomup/remoe_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 79 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.05 --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 4

# DeepSeek
export EXP_NAME=deepseek_05b_gated_d64_s128_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_deepseek_nomup/deepseek_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 79 --moe-ffn-hidden-size 42 --moe-router-topk 16 --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 16
export EXP_NAME=deepseek_05b_gated_d64_s128_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_deepseek_nomup/deepseek_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 79 --moe-ffn-hidden-size 42 --moe-router-topk 16 --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 16

# BlockFFN (v1)
export EXP_NAME=blockv1_05b_mul1001_d64_s128_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_blockffn_v1_nomup/blockv1_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 77 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.001 --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 16
export EXP_NAME=blockv1_05b_mul1001_d64_s128_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_blockffn_v1_nomup/blockv1_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 77 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.001 --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 16

# TopP
export EXP_NAME=topp_05b_d64_s128_nongated_p06_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_topp_nomup/topp_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 79 --moe-ffn-hidden-size 63 --moe-router-topp 0.6 --expert-not-gated --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 4
export EXP_NAME=topp_05b_d64_s128_nongated_p06_lr78e4_b256; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_topp_nomup/topp_05b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 79 --moe-ffn-hidden-size 63 --moe-router-topp 0.6 --expert-not-gated --lr 7.8e-4 --global-batch-size 256 --micro-batch-size 4

# ====== 1.2B ======
# DECO (BlockFFN-v2)
export EXP_NAME=blockffn_12b_mul1001_withmean_d64_s128_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_blockffn_nomup/blockffn_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 102 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.001 --expert-act-func norm_silu --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 16 --train-iters 23000 --lr-decay-iters 23000
export EXP_NAME=blockffn_12b_mul1001_withmean_d64_s128_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_blockffn_nomup/blockffn_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 102 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.001 --expert-act-func norm_silu --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 16 --train-iters 23000 --lr-decay-iters 23000

# Dense
export EXP_NAME=dense_12b_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_dense_nomup/dense_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 16 --train-iters 23000 --lr-decay-iters 23000
export EXP_NAME=dense_12b_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_dense_nomup/dense_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 16 --train-iters 23000 --lr-decay-iters 23000

# BlockFFN (v1)
export EXP_NAME=blockv1_12b_mul1001_d64_s128_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_blockffn_v1_nomup/blockv1_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 102 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.001 --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 16 --train-iters 23000 --lr-decay-iters 23000
export EXP_NAME=blockv1_12b_mul1001_d64_s128_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_blockffn_v1_nomup/blockv1_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 102 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.001 --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 16 --train-iters 23000 --lr-decay-iters 23000

# ReMoE
export EXP_NAME=remoe_12b_mul105_d64_s128_nongated_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_remoe_nomup/remoe_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 102 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.05 --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 4 --train-iters 23000 --lr-decay-iters 23000 --router-clamp-act-ratio 0.5
export EXP_NAME=remoe_12b_mul105_d64_s128_nongated_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_remoe_nomup/remoe_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 102 --moe-ffn-hidden-size 64 --expert-not-gated --router-entropy-loss-coeff 1e-8 --router-entropy-loss-coeff-resume 0 --router-entropy-loss-coeff-multiplier 1.05 --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 4 --train-iters 23000 --lr-decay-iters 23000 --router-clamp-act-ratio 0.5

# DeepSeek
export EXP_NAME=deepseek_12b_d64_s128_gated_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_deepseek_nomup/deepseek_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 101 --moe-ffn-hidden-size 43 --moe-router-topk 20 --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 16 --train-iters 23000 --lr-decay-iters 23000
export EXP_NAME=deepseek_12b_d64_s128_gated_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_deepseek_nomup/deepseek_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 101 --moe-ffn-hidden-size 43 --moe-router-topk 20 --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 16 --train-iters 23000 --lr-decay-iters 23000

# TopP
export EXP_NAME=topp_12b_d64_s128_nongated_p06_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node1 WORLD_SIZE=2 RANK=0 bash examples/blockffn/scaling_topp_nomup/topp_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 102 --moe-ffn-hidden-size 64 --moe-router-topp 0.6 --expert-not-gated --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 2 --train-iters 23000 --lr-decay-iters 23000
export EXP_NAME=topp_12b_d64_s128_nongated_p06_lr654e4_b512; export FOLDER=results/${EXP_NAME}; source examples/data_conf/example_data.sh && MASTER_ADDR=node2 WORLD_SIZE=2 RANK=1 bash examples/blockffn/scaling_topp_nomup/topp_12b.nvidia.sh --tensorboard-dir ${FOLDER}/tensorboard/ --save ${FOLDER}/checkpoints/ --moe-shared-expert-intermediate-size 128 --num-experts 102 --moe-ffn-hidden-size 64 --moe-router-topp 0.6 --expert-not-gated --lr 6.54e-4 --global-batch-size 512 --micro-batch-size 2 --train-iters 23000 --lr-decay-iters 23000
